### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by BjornW** [vc4all/site#12]
Als we meerdere servers hebben gaan we pas een lijst toevoegen. Tot die tijd maken we een knop / link met "Start je beeldgesprek". Als we meer servers hebben kunnen we op mbv javascript automagisch random een server kiezen die dan aan het klik event van de knop wordt gekoppeld. Zo wordt er voor de gebruiker automatisch een server gekozen.

**Comment by BjornW** [comment]
Momenteel wordt er al wel automatisch een random nummer gegenereerd en die wordt gebruikt als kamer nr. Dit moet ik nog uitbreiden naar een selectie van server.

**Comment by berkes** [comment]
@BjornW dit was toch af?

**Comment by BjornW** [comment]
yep
