### ISSUE TITLE
Overhaul homepage

### ISSUE THREAD

**Issue by berkes** [vc4all/site#16]
* [x] Resize and pngcrush logo.png to match used size.
* [x] colorscheme -primary -secondary to match with logo.
* [x] Selector filled from servers.json file.
* [x] Selector gets random selection.
* [x] Choose layout from layouts for page.
* [x] beeldbellen.md content page using page layout. Linked to, from [meer over beeldbellen].
* [x] privacy.md content page explaining privacy and security measures and benefits.
* [x] handleiding.md content page explaining how to install apps, or use jitsi. 
* [x] find a place to list the servers. servers.md content? section below the payoff? loaded from same servers.json file?
* [x] Place the Random-room-number-name maker back into the main action-button on homepage.
* [x] Fix TODOs in texts: 'werkt' opdelen in simpel/snel en lange uitgebreide text.
* [x] Fix TODOs in texts: 'privacy' voordelen jitisi + call to action.
* [x] Place Contact back into site: on homepage with Call To Action and Payoff (Eigen Jitsi server?.... etc)

Note: the content pages should *not* get an overhaul yet from the content we already have: just move that content in there. Improving that content is another ticket alltogether. E.g. we should not postpone releasing this layout because we want to have a nice illustrated manual.

---

Test with N=2

* Start a new call from https://vc4all.nl
* Start a new call from https://beeldbellen.vc4all.nl
* Please explain your initial thoughts (nothing is wrong, every thought is valid)

1: 
* Nice logo. But why all the text. I don't want to read, I want to make a call.
* Good one. What is jitsi? Well. Nice that you can just hit enter and have a room (BK: I did not know that, but since the field has the focus it works indeed).

2: 
(also see ticket #15 )
* I don't see where to start a call. (BK: after some help it worked)
* A there it is. What a strange name, is that a password? It looks like those passwords you (BK: that's me) always has (BK: I use passphrases with weird words, person knows this).

--- 

We should probably try to distinguish the explanations and details over the "call to action". There's lots of information all shouting for attention, with little hierarchy: all information seems just as important.

I'd suggest to first wireframe a simple page. With *one* goal in mind: get people to quickly make a call. All other stuff is secondary (covid, other servers, android, etc).

Note that people who open an invitation mail on mobile already get sent to the playstore to install the app (N=6, 3 people -very non-technical- got the app after I invited them, without me explaining anything.)

**Comment by BjornW** [comment]
I agree, but within the constraints of the current Hugo setup this is the best I could do for now. If we want to make the homepage better we might need to switch to either a better suited theme or plain html.

**Comment by berkes** [comment]
Initial setup: 
![afbeelding](https://user-images.githubusercontent.com/77059/78552488-e2005c00-7807-11ea-8142-60b999abcf86.png)

**Comment by BjornW** [comment]
Mooie 1e opzet ik ga er even mee spelen.

**Comment by berkes** [comment]
> Mooie 1e opzet ik ga er even mee spelen.

Zit dus in hierboven gelinkete branch/PR.

**Comment by BjornW** [comment]
Opmerkingen nieuwe vormgeving: 

1. Logo vind ik teveel ruimte innemen voor iets wat eigenlijk niet zo heel belangrijk is. Het is puur branding.
2. Direct beeldbellen vind ik te weinig 'uniek', de knoppen lijken nu allemaal even belangrijk. Die zou zich meer moeten onderscheiden.
3. Direct beeldbellen moet duidelijker zijn dat dit via een partner gaat en dat wij hiervoor niet verantwoordelijk zijn. Dat is nu met huidige vormgeving ook niet goed.
4. De 3 kolommen en de 'rust' die in dit ontwerp zit vind ik heel prettig. 
5. Waar gaan we de bestanden content plaatsen, worden dit losse nieuwe pagina's?

**Comment by berkes** [comment]
>     1. Logo vind ik teveel ruimte innemen voor iets wat eigenlijk niet zo heel belangrijk is. Het is puur branding.


 Ik heb nu een versie met stockfoto, dat maakt het een stuk rustiger en mooie IMO.
Zonder stockfoto het logo in een hoek wegdrukken ziet er raar en kaal uit.


>     2. Direct beeldbellen vind ik te weinig 'uniek', de knoppen lijken nu allemaal even belangrijk. Die zou zich meer moeten onderscheiden.

De knop heet "nieuwe vergadering aanmaken". 
In de geüpdate versie zijn de andere knoppen nu "secondary". 

>     3. Direct beeldbellen moet duidelijker zijn dat dit via een partner gaat en dat wij hiervoor niet verantwoordelijk zijn. Dat is nu met huidige vormgeving ook niet goed.

Vandaar de dropdown. Wat stel je voor om het nog verder te verbeteren?

>     4. De 3 kolommen en de 'rust' die in dit ontwerp zit vind ik heel prettig.
>     5. Waar gaan we de bestanden content plaatsen, worden dit losse nieuwe pagina's?

De Cards (kolommen) hebben allemaal een call-to-action en die linken naar secondaire pagina's. Zoals hierboven te zien in de todo's, moeten dat aparte pagina's worden.

![afbeelding](https://user-images.githubusercontent.com/77059/79116695-7c711a00-7d89-11ea-8ad0-ba060a614c11.png)

**Comment by berkes** [comment]
Content pages:

![Screenshot_2020-04-15 Wat is VC4ALL - VC4ALL — Videobellen voor iedereen](https://user-images.githubusercontent.com/77059/79324844-81140a80-7f10-11ea-9baf-d55809f570dd.png)


![Screenshot_2020-04-15 Servers - VC4ALL — Videobellen voor iedereen](https://user-images.githubusercontent.com/77059/79324842-807b7400-7f10-11ea-8d65-9dcd4ce80f3a.png)
