### ISSUE TITLE
Jitsi in het Nederlands vertalen

### ISSUE THREAD

**Issue by BjornW** [vc4all/site#2]
Ivm de doelgroep waarbij niet iedereen het Engels even machtig is.

**Comment by BjornW** [comment]
Set defaultLanguage: 'en', in https://github.com/jitsi/jitsi-meet/blob/master/config.js#L271 naar 'nl' Inmiddels aangepast

**Comment by berkes** [comment]
Hier is de vertaling: https://github.com/jitsi/jitsi-meet/blob/master/lang/main-nl.json

**Comment by berkes** [comment]
> Set defaultLanguage: 'en', in https://github.com/jitsi/jitsi-meet/blob/master/config.js#L271 naar 'nl' Inmiddels aangepast

Is dat in ansible te doen? Moet dat in de /etc/nogwat file?

**Comment by BjornW** [comment]
ja in /etc/meet/vc4all.nl-config.js (naam is instantie gebonden zo te zien)
