### ISSUE TITLE
Meet.jit.si is being indexed by Google

### ISSUE THREAD

**Issue by BjornW** [vc4all/site#21]
* [ ] Upload a robots.txt through ansible in the /var/... directories, next to e.g. the config.js file
* [ ] Link that with an `alias` in the nginx.conf, same as config.js.
* [ ] See if jitisi-meet-ansible role upstream wants this too: If so, make a PR there.
* [ ] See if jitsi-meet repo does not want this robots.txt in their main repo. If so, make a PR there.

---

Got this email from someone (not sure if they want to be named here) 

" meet.jit.si wordt vrolijk geïndexeerd door google:
> https://www.google.com/search?q=site:/meet.jit.si&lr=&hl=en&sxsrf=ALeKk03pGLidwg94Q_igBIUxRXsOiONtzg:1585740118772&source=lnt&tbs=qdr:w&sa=X&ved=2ahUKEwiT3fCjjsfoAhXNKewKHQFDA9cQpwV6BAgGEBw&biw=1920&bih=938
> 
> Misschien wil je om soortgelijke indexering te voorkomen een robots.txt
> gebruiken." 

I find it a bit weird since a room should only exist for a short while, but I agree it could not hurt to use a robots.txt (although these do not enforce anything...)

**Comment by berkes** [comment]
> I find it a bit weird since a room should only exist for a short while, but I agree it could not hurt to use a robots.txt (although these do not enforce anything...)

It could very well be listed on forums, on a website, in a public agenda, on public report (notulen) etc. 

There are lots of reasons why people would publish their room, after which Google will pick it up. 
Reversed: if a room-link was not published, there's no way Google can¹ or more precise: will index it.  So, I'm quite sure that all those indexed rooms were published by people themselves. 

We can avoid this with a `robots.txt`. This brings three downsides:

1. We'd probably need to open a Google Search console instead to tune this even better: Google itself advices this (WC-eend?)
1. If google won't index it, people might still have published their rooms and less-nice indexers will still have it. It might give a false sense of security. Robots.txt is never a security measure.
1. There might be legitimate reasons why people want it indexed. E.g. public "vrijmibo" or the local Linux User Group meeting up (this is real and practical: https://linuxnijmegen.nl/bijeenkomsten/114-lugn92-dinsdag-14-april-2020). We are "Denying" them the indexing.

I'd say the downsides are small and the benefits outweight those downsides though. So: I'm all for a robots.txt.

--- 

¹ Technically Google could pick Room-URLS from gmail, Google calendar, Chrome, Android etc. But they don't: if an URL is not published, they won't follow it. This is still Googles practice.
