### ISSUE TITLE
Jitsi servers spreadsheet

### ISSUE THREAD

**Issue by berkes** [vc4all/site#22]
Inmiddels spreadsheet aangemaakt op https://lite.framacalc.org/9fr0-jitsi-servers Nu nog verder vullen

See https://github.com/vc4all/site/issues/17

**Comment by berkes** [comment]
Consider deprecating for https://ladatano.partidopirata.com.ar/jitsimeter/ 

Which has:
* Ranking
* Community traction
* A workflow to add servers
* A much larger selection.

**Comment by BjornW** [comment]
I suggest closing this issue. As you've mentioned there is a better alternative for those seeking Jitsi servers. Let us focus on our smaller curated list. We can mention this project for those wanting to talk with relatives abroad. @berkes Agree?
