### ISSUE TITLE
Create common contact@ emailaddress instead of linking to our respective homepages.

### ISSUE THREAD

**Issue by berkes** [vc4all/site#26]
We need generic email-addresses and one where people can contact us.

- admin@vc4all.nl, abuse@vc4all.nl and postmaster@vc4all.nl.
- contact@vc4all.nl

Contact@ must then be used as contact email on the website:

* [ ] in the config.toml; with an icon - see example site config in theme.
* [ ] in the contact area.
* [ ] alternatively revert the commit that removes exception for "contact.md" and use config instead of contact.md. see if adding contact from toml is styled well enough.

We can use my mailserver, but for outgoing mail, I then need to be the DNS manager of the vc4all domain.

**Comment by berkes** [comment]
We then have two options:

- forward to bjorn and ber.
- manage a shared inbox.

I'd prefer the latter because it allows us to manage the communication by introducing tags, folders or some other simple system.

**Comment by BjornW** [comment]
For outgoing email I want to use the one from Transip. For incoming I'd prefer aliases, but i can live with a shared inbox if it has imap :)

**Comment by berkes** [comment]
> For outgoing email I want to use the one from Transip. For incoming I'd prefer aliases, but i can live with a shared inbox if it has imap :)

You can set the SMTP server any way you want in your client. 

My mailserver needs either access to the DNS (become the NS for the vc4all domain) OR it requires a long list of manual DNS entries to be set and maintained. 

Nameservers:
ns1.fairfax.webschuur.com | 172.105.87.157 | 2a01:7e01:0000:0000:f03c:92ff:fef1:c4e6
ns2.fairfax.webschuur.com | 172.105.87.157 | 2a01:7e01:0000:0000:f03c:92ff:fef1:c4e6

Let me know what you want. If we move the DNS, I need to know, 24h in advance, what DNS records to set (other than email records).

**Comment by BjornW** [comment]
I don't want to move DNS. We can use the outgoing smtp server from Transip for Munin. We can use our own for contact info as it is now with both our sites listed. I prefer to focus on the other open issues. What do you think @berkes?

**Comment by berkes** [comment]
>  prefer to focus on the other open issues. 

What issues we should focus on is determined by the ordering of issues in https://github.com/orgs/vc4all/projects/1

> We can use the outgoing smtp server from Transip for Munin. 

This is purely an issue for incoming email. Issue for outgoing email (munin) is here: https://github.com/vc4all/ansible/issues/9

> We can use our own for contact info as it is now with both our sites listed.

I find this confusing for people. I've had three separate people telling me this in person. 

Users want to "contact" they don't want to have to:
1. choose who to contact. Then,
2. follow the link to that users homepage, then
3. search there, how to contact that person.

Having one "contact@" email is a simple and good solution.

For which we need an inbox or a forward setup. Meaning: it needs a mailserver. 
Running a mailserver, even incoming, requires changes to the DNS. 

In addition, one should have `abuse` and `postmaster` as outlined by various RFCs and best practices, if one runs a mailserver. Most mailservers handle this for you.

Those can be done manually, or  left to the mailserver. In the first case: the DNS records as provided by the mailserver must be added manually to the DNS. In the second case: the mailserver will add the records itself.

**Comment by BjornW** [comment]
Er is nog een reden om geen email adres zo direct op de site te zetten en dat is een kleine drempel opwerpen om zo hoeveelheid mail te beperken. Daarom zet ik dit issue nu onderaan de lijst.
