### ISSUE TITLE
Create and choose a logo

### ISSUE THREAD

**Issue by berkes** [vc4all/site#7]
E.g. from https://mybrandnewlogo.com/nl/logo-ontwerpen OR https://app.brandmark.io/v2/

![afbeelding](https://user-images.githubusercontent.com/77059/77154717-852d4380-6a9c-11ea-933d-5a627f6fcc89.png)

**Comment by berkes** [comment]
Favorite options:
![afbeelding](https://user-images.githubusercontent.com/77059/77170441-56729580-6abb-11ea-9710-2f4e09719a0e.png)

![afbeelding](https://user-images.githubusercontent.com/77059/77172076-b10cf100-6abd-11ea-8500-301181d0e243.png)

![afbeelding](https://user-images.githubusercontent.com/77059/77172100-bcf8b300-6abd-11ea-8e24-19e7a3add839.png)

![afbeelding](https://user-images.githubusercontent.com/77059/77172147-cda92900-6abd-11ea-87c2-6aa6b303f475.png)

**Comment by BjornW** [comment]
@berkes 
![77172100-bcf8b300-6abd-11ea-8e24-19e7a3add839](https://user-images.githubusercontent.com/65042/77226718-baa85e80-6b7a-11ea-9616-086a6dfd25e4.png) is mijn favoriet. Ik ga nu ff checken of het genoeg contrast heeft ivm toegankelijkheid.

**Comment by BjornW** [comment]
Contrast is nog niet helemaal ok. Ik zou het blauw zo laten icl rode hartje en de achtergrond wit maken. Dan werkt het waarschijnlijk beter ivm kleurenblindheid enzo.

**Comment by berkes** [comment]
![logo](https://user-images.githubusercontent.com/77059/77227300-99963c80-6b7f-11ea-93ed-9c9c055a2e59.png)

Deze zit nu in de site repo.

**Comment by BjornW** [comment]
Perfect!
